#!/usr/bin/env bash
set -eux

LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | \grep -Po '"tag_name": *"v\K[^"]*')
curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/download/v${LAZYGIT_VERSION}/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
tar xf lazygit.tar.gz lazygit
install lazygit -D -t ~/bin/
rm lazygit.tar.gz lazygit
# Download and install Micro Editor (x86_64)
curl -Lo micro.tar.gz "https://github.com/micro-editor/micro/releases/download/v2.0.15/micro-2.0.15-linux64.tar.gz"
tar -xzf micro.tar.gz --strip-components=1 "micro-2.0.15/micro"
install micro -D -t ~/bin/
rm micro.tar.gz micro

chmod a+x ./start
echo 'git config --global user.name "Bikash"' >> ~/.bashrc
echo 'git config --global user.email "bikashprakashdash@gmail.com"' >> ~/.bashrc

mkdir -p ${NB_PYTHON_PREFIX}/share/jupyter/lab/settings
mv overrides.json ${NB_PYTHON_PREFIX}/share/jupyter/lab/settings
